### ISSUE TITLE
Usage instructions aren't working

### ISSUE THREAD

**Issue by sirspock** [mintproject/MINT-Transformation#78]
```
docker run --rm -p 5000 -v $(pwd):/ws -it mint_dt bash
Traceback (most recent call last):
  File "/opt/conda/envs/mintdt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/mintdt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ws/dtran/main.py", line 50, in <module>
    cli()
  File "/opt/conda/envs/mintdt/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/mintdt/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/mintdt/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/mintdt/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/mintdt/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/mintdt/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/ws/dtran/main.py", line 37, in exec_pipeline
    parsed_pipeline, parsed_inputs = parser.parse(path=config)
  File "/ws/dtran/config_parser.py", line 163, in parse
    raise Exception(f"Unsupported file format for{path}. Only supports json or yaml file")
Exception: Unsupported file format forbash. Only supports json or yaml file
```

**Comment by sirspock** [comment]
The instructions are outdated

**Comment by minhptx** [comment]
@sirspock The ReadMe is updated. Thanks.
